In [1]:
import numpy as np

In [3]:
mat = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(mat.dtype)

int64


In [7]:
fmat = mat.astype(float)
print(fmat.dtype)

float64


In [12]:
v =np.array([3,2,5,1])

mat = np.array([[1,2,3],
               [4,5,6],
               [7,8,9],
               [0,0,0]])
mat[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [13]:
mat = np.zeros((3,4))
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
mat = np.ones((3,4))
mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
mat =np.arange(0,361,90)
mat

array([  0,  90, 180, 270, 360])

In [19]:
I =np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.random.random((3,4))


array([[0.69399897, 0.62252765, 0.15193614, 0.39834719],
       [0.47159376, 0.35274045, 0.85054073, 0.59835547],
       [0.17342399, 0.41013349, 0.1610568 , 0.4594881 ]])

In [21]:
np.random.randint(0,11,(5,5))

array([[ 8,  8,  1,  6,  9],
       [ 6,  3,  3,  2,  4],
       [ 0,  0, 10,  3,  8],
       [ 6,  9,  6,  7,  0],
       [ 0,  7, 10,  6,  5]], dtype=int32)

In [ ]:
mat1 = np.zeros((3,4))
mat2 = np.zeros((5,3))
np.savez('np_file' ,Ones_Mat = mat1 , Zero_Mat =mat2)

In [25]:
with np.load("np_file.npz") as file:
    Mat_1 = file['Ones_Mat']
    mat_2 = file['Zero_Mat']

print(Mat_1)
print(mat_2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [1]:
def array_reshape(arr, rows =-1 , cols =-1):
    try:
        arr = np.array(arr)
        return arr.reshape(rows, cols)
    except (TypeError, ValueError) as e:
        raise ValueError(f"Invalid reshape operation: {e}")

In [27]:
vec = [1,2,3,4,5,6]
print(array_reshape(vec ,2 ,3))

[[1 2 3]
 [4 5 6]]


In [28]:
v= np.array([1,2,3,4,5,0])
np.all(v>=1)

np.False_

In [30]:
v=  np.array([1,2,3,4,5])
v2= np.array([5,2,0,4,1])
np.isclose(v,v2 ,atol = 1)

array([False,  True, False,  True, False])

In [35]:
v = np.array([2,4,1,5,10])
condition = v >= 4
new_arr =np.where(condition, -1 , v)
print(new_arr)


[ 2 -1  1 -1 -1]
