# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [15]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    arr=[]
    if mode =='zeros':
        arr=np.zeros(shape)
    elif mode =='ones':
        arr=np.ones(shape)
    elif mode =='full':
        arr=np.full(shape,value)
    elif mode =='identity':
        arr=np.identity(shape)
    return arr

print(array_factory('zeros',(3,3)))
print('==============================')
print(array_factory('ones',(3,3)))
print('==============================')
print(array_factory('full',(3,3),7))
print('==============================')
print(array_factory('identity',3))
print('==============================')


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [29]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        # Convert inputs to ndarray to ensure they are processed as Tensors 
        # arr = np.array(data1)

        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # Rule: Change the shape of arr1 to new_shape 
        # Common usage: turning a vector (1D) into a matrix (2D)  by using reshape function 
        reshaped_arr1 = arr1.reshape(new_shape)
        reshaped_arr2 = arr2.reshape(-1 , reshaped_arr1.shape[1])

        # Rule: Vertical Stacking (vstack) 
        # Requirement: Both matrices must have the same number of columns
        combined_dataset = np.vstack([reshaped_arr1,reshaped_arr2])

        return combined_dataset

    except ValueError as e:
        # Handle cases where reshape size doesn't match or stack columns don't match
        raise ValueError(f"Company-grade Error: {e}")

data1 = [1,2,3,4,5,6]
data2 = [2,4,6,5,7,8,1,9]

print(secure_reshape_and_stack(data1,data2,(3,2)))

[[1 2]
 [3 4]
 [5 6]
 [2 4]
 [6 5]
 [7 8]
 [1 9]]


part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [2]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold) 
    and replaces them with a new value.
    """
    # 1. Convert input to a numpy array (ndarray)
    
    arr = np.array(arr)
    
    if  np.isscalar(threshold):
        condition = arr >= threshold
        modified_arr =np.where(condition ,replacement_value ,arr)
        return modified_arr
        
    threshold =np.array(threshold)
    replacement_value = np.ones(replacement_value)
        
    reshape_Arr =arr.reshape(threshold.shape[0],-1)

    # 2. Define the condition: elementwise comparison 
    # This creates a Boolean numpy array 
    condition = reshape_Arr >= threshold
    
    # 3. Apply Modification using np.where() 
    # np.where(condition, value_if_true, value_if_false)
    modified_arr = np.where(condition ,replacement_value,reshape_Arr)
    
    return modified_arr

In [4]:
# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6] 

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = [[7, 8, 9], 
            [10, 11, 12]]

# Reshape A to 2x3 and stack with B
final_report = apply_threshold(branch_a, branch_b, (2, 3))
final = np.vstack([final_report , branch_b])
print(final)
# Resulting shape: (4, 3)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


TestCase

In [ ]:
# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6] 

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = [[7, 8, 9], 
            [10, 11, 12]]

# Reshape A to 2x3 and stack with B
final_report = apply_threshold(branch_a, branch_b, (2, 3))
print(final_report)
# Resulting shape: (4, 3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


: 

In [26]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])